db:
    username: "scheduleuser"
    host:     "172.17.0.1"
    port:     "5432"
    dbname:   "scheduledb"
    sslmode:  "disable"
    password: "12345"
medication_period:
    period : "3h"
    start:   "08:00:00"
    end:     "22:00:00"
logs:
    logfile: "app.log"