db:
    username: "scheduleuser"
    host:     "localhost"
    port:     "5432"
    dbname:   "postgres"
    sslmode:  "disable"
    password: "12345"
medication_period:
    period : "3h"
    start:   "08:00:00"
    end:     "22:00:00"
logs:
    logfile: "app.log"