services:
  api:
    container_name: schedule-app
    image: golang:1.23-alpine
    build:
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:8080"
      - "9000:9000"
    depends_on:
        postgres:
          condition: service_healthy
  postgres:
    image: postgres
    container_name: schedule_app_db
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scheduleuser -d scheduledb"]
      interval: 7s
      timeout: 5s
      retries: 5
volumes:
  db-data:
    name: 'schedule-app'